app:
  build: .
  command: sh docker/start.sh
  volumes:
    - .:/usr/src/app
    - ./config/database.yml.default:/usr/src/app/config/database.yml
    - ./bundle:/usr/local/bundle
    - ./public:/usr/share/nginx/html/logdatanotes
    - /home/david/uploads/logdatanotes:/usr/src/app/public/uploads
    - tmp:/usr/src/app/tmp
    - "/var/run/postgresql:/var/run/postgresql"
    - "../../dumps:/usr/src/app/dumps"
    - "../../logs:/usr/src/app/log"
  env_file:
    - database.env
  environment:
    RAILS_ENV: "${RAILS_ENV}"
    REDIS_URL: redis://redis:6379/
  restart: always
nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./public:/usr/share/nginx/html/logdatanotes
    - /home/david/uploads/logdatanotes:/usr/share/nginx/html/logdatanotes/uploads
    - "/share/logs/logdatanotes_${RAILS_ENV}:/usr/src/app/log"
    - /home/david/ssl_certificates/logdatanotes:/usr/share/nginx/html/ssl_certificates/logdatanotes
  ports:
    - "3001:3001"
  expose:
    - "3001"
  restart: always
