default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 5
  prepared_statements: false
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
